### ISSUE TITLE
ci: add code coverage

### ISSUE THREAD

**Issue by madiedgar** [legesher/tree-sitter-legesher-python#10]
## Code Coverage
>Quality code > 💯 code coverage

Though attaining and maintaining a 💯code coverage report is a great goal to set, we want the focus to rather be on code quality. Code coverage with a repository that changes the identifying features of a language makes it a little more difficult to report on code coverage, but open for ideas / suggestions / pull-requests.

**Comment by LeonardoFurtado** [comment]
Why not use coveralls.io?

**Comment by madiedgar** [comment]
That's a great suggestion @LeonardoFurtado! I've never used coveralls before, would you want to open a pull request and test it out? 😄

**Comment by LeonardoFurtado** [comment]
I will do it :)

**Comment by madiedgar** [comment]
Hey @LeonardoFurtado! Thanks for contributing to issue #16! 🎉 Can I help in anyway for this one?

**Comment by GauravMohla** [comment]
@madiedgar can I look into this issue?

**Comment by madiedgar** [comment]
Yes that would be helpful @GauravMohla !

**Comment by madiedgar** [comment]
Hey @GauravMohla & @LeonardoFurtado , any update on this? We've made a couple of major updates with correlation to the updates from the `tree-sitter-python` repo.

**Comment by mohitsaxenaknoldus** [comment]
Hey @madiedgar can I work on this?

**Comment by tuhinmallick** [comment]
Is this issue still open then I would like to work on it
