### ISSUE TITLE
marketing: add project to "awesome-for-beginners"

### ISSUE THREAD

**Issue by madiedgar** [legesher/tree-sitter-legesher-python#12]
## Awesome-For-Beginners

Would love to add this repository to the python section for the [`awesome-for-beginners`](https://github.com/MunGell/awesome-for-beginners#python) repository for new programmers / open sourcers to learn about contributing to Legesher. 

Please use label: `good-first-issue` or `Opportunity: Technical Beginner`. More details can be found in their pull request template.

**Comment by wescran** [comment]
Hello, I would like to help with this issue if it is still available :)

**Comment by madiedgar** [comment]
Awesome @wescran, that would be great! Let me know if you need any help 😄I'll assign you to this issue. 👍

**Comment by wescran** [comment]
@madiedgar I am just about ready to make the PR on the [`awesome-for-beginners`](https://github.com/MunGell/awesome-for-beginners#python) repository. The link needs a project description and I just wanted to run this by you before submitting.
> This software uses the written language interchangeable version of the tree-sitter grammar for Python, allowing the user to write Python code in their native language.

What do you think? Or would you prefer something else?

**Comment by madiedgar** [comment]
Thanks @wescran for checking in! Hmm, this is the fun part 🤔. We're still working on how to introduce more advanced topics like compilers and programming language grammars to a beginner audience. What do you think about simplifying the description to highlight the ability to `learn and code in Python using your native language`?

**Comment by wescran** [comment]
Okay thanks for the input! I have shortened the description to what you suggested. I will make the PR shortly.

**Comment by madiedgar** [comment]
Awesome, thanks @wescran 👍

**Comment by wescran** [comment]
The PR has been merged, you can see the entry [here](https://github.com/MunGell/awesome-for-beginners#python)! Let me know if there is anything else I need to do for this issue.

**Comment by madiedgar** [comment]
Amazing!!! Thank you so much! I'm adding `allcontributors` to the project, so you can get credit for this within our project as well (and get you another pull request!). I'll update you when that's configured 😄 Thanks again!!

**Comment by madiedgar** [comment]
In the meantime, thank you @wescran!  🎉🎉🎉 ❤️ THANK YOU THANK YOU THANK YOU ❤️ We'd love to celebrate you and your contribution to the community. Let us say "Thank You" again, by sending you a [special gift](https://madi357705.typeform.com/to/wzub4R)!

We couldn't thank you enough for your contribution. We hope you continue sharing your gifts and knowledge with not just us, but with the world around you.😍
