### ISSUE TITLE
marketing: add repository to "awesome-for-non-programmers"

### ISSUE THREAD

**Issue by madiedgar** [legesher/tree-sitter-legesher-python#13]
## Awesome-For-Non-Programmers

Would love to add this repository to the [`awesome-for-non-programmers`](https://github.com/szabgab/awesome-for-non-programmers) repository for non programmers to learn about open source opportunities that don't require a technical background. 

With the Legesher project, there are a lot of opportunities for people of all backgrounds to contribute the skills they either want to grow in or give back. With a strong emphasis on written language translation, individuals who are bilingual have a great space to contribute. Individuals who want to grow in community development, marketing, writing impactful pieces of insight, or just want to learn more about the tech world have ample amounts of opportunities here as well! 

More details can be found in their pull request template.

**Comment by jonathan-alvaro** [comment]
Can I be assigned to this?

**Comment by madiedgar** [comment]
Absolutely @jonathan-alvaro! 👍

**Comment by jonathan-alvaro** [comment]
I think someone already made a PR for this @madiedgar

**Comment by madiedgar** [comment]
Yes, thanks for checking! @Navneet78 made a pull request to add the `legesher-dot-io` repository to the list. Since there are a lot of items for non-programmers for all of the Legesher repositories, I added the same issue on each repo.

Not sure what the maintainers of the `awesome-for-non-programmers` do for multiple repositories of an organization. 🤷‍♀If you can look into that, I'll assign you to all the similar issues in the other repositories so we don't have duplicates. 😄

**Comment by startonmonday** [comment]
Hi! I'm a native Russian speaker. I can help with translation with pleasure.

**Comment by madiedgar** [comment]
That's awesome @startonmonday! The hub of translations are made in the [`legesher-translations`](https://github.com/legesher/legesher-translations) repo. I'll make an issue for you 😄 [`Add New Dialect: Russian (Python)`](https://github.com/legesher/legesher-translations/issues/20)

**Comment by madiedgar** [comment]
Closing this issue as the maintainer of `awesome-for-non-programmers` won't accept the pull requests. [see here](https://github.com/legesher/legesher/issues/54)
