### ISSUE TITLE
💻 🎃 Welcome to Hacktoberfest 2019🎃 💻 

### ISSUE THREAD

**Issue by madiedgar** [legesher/tree-sitter-legesher-python#14]
![image](https://user-images.githubusercontent.com/7844510/65824802-ae32f100-e23c-11e9-838a-dc28384dcce7.png)

# Welcome to [Hacktoberfest](https://hacktoberfest.digitalocean.com/)
..and welcome to our community! So many fun things to get into this Hacktoberfest like [adding translations for your native written language 🌏 ](https://github.com/legesher/legesher-translations), [sharpening & sharing your python skills 🐍 ](https://gtihub.com/legesher/tree-sitter-legesher-python) or even [helping foster our community 📸  by creating instastories or managing our communication channels ❤️](https://github.com/legesher/legesher-pride)!

**Stay in the know**
New issues are added every day with varying difficulty levels for varying skillsets. Get notified of updates by clicking the `👁‍🗨 watch` button and save the repo for later reference by clicking the `⭐️ star` button at the top right corner of this repo! 

## Ways to get involved
Legesher is a growing project with many different ways to get involved. Below is a list of all of the repositories that are participating in Hacktoberfest. Search by _label_ to find issues that are in the area of your expertise or an area you're wanting to learn / grow in!

| Project | Purpose |
|---------|---------|
| [`tree-sitter-legesher-python`](https://github.com/legesher/tree-sitter-legesher-python) | Tree-sitter python grammar used by text editors allowing Legesher's languages to be implemented |
| [`language-legesher-python`](https://github.com/legesher/language-legesher-python) | Atom's programming language binding to allow syntax highlighting, code folding etc. to a specific grammar |
| [`legesher-translations`](https://github.com/legesher/legesher-translations) |  Host and API of all the language translations for written languages for code keywords / concepts |
| [`legesher-dot-io`](https://github.com/legesher/legesher-dot-io) | Legesher's public [website](https://legesher.io) |
| [`legesher-pride`](https://github.com/legesher/legesher-pride) | Community-focused initiatives to add more value (and members) to our pride |
| [`legesher-docs`](https://github.com/legesher/legesher-docs) | Legesher's documentation hub. Will be transitioning to a documentation host soon. |
| [`legesher`](https://github.com/legesher/legesher) | Git integration to collaborate with code and others in other languages |

### Important Hacktoberfest Information
- Be sure to sign up at [https://hacktoberfest.digitalocean.com](https://hacktoberfest.digitalocean.com) so you can qualify for your free shirt(👚!!)
- Create a Pull Request between October 1-31 of 2019 to count towards your 4 PRs
- See [Contributing Guidelines](https://github.com/legesher/legesher/blob/master/CONTRIBUTING.md)
- See https://hacktoberfest.digitalocean.com/details for more details

🎁 If you contribute to a Legesher repository, then you will receive a handwritten letter from our [founder](https://www.instagram.com/withmadico/) expressing her deepest gratitude. You might also find some special edition stickers 👀.

As always, feel free to comment or ask any questions here as well.

**Comment by ShubhamRattra** [comment]
can i contribute in this

**Comment by madiedgar** [comment]
Absolutely @ShubhamRattra! What types of contribution do you want to make? Is there a specific language / topic you're wanting to learn more about or work in ?

**Comment by arian81** [comment]
I want to contribute to this project but I'm a total beginner so I don't know how to help

**Comment by madiedgar** [comment]
You're in the perfect place @arian81! Let's start with [this issue](https://github.com/legesher/legesher/issues/53) and I'll walk you through it! 😄

**Comment by Aadithyavarma** [comment]
Hi all,
I want to contribute to this project. I have some experience in Python but I am totally new to open source contributing. So some one please help me find a bug and what are the steps to take it up.

**Comment by elissavetv** [comment]
Hi! I want to contribute as well! I am working on Python! :)

**Comment by madiedgar** [comment]
Amazing!! Welcome @Aadithyavarma and @elissavetv 👋 Python is our jam right now. lol 😉. Let me release a couple of python issues for y'all! They will most likely be within the [`tree-sitter-legesher-python`](https://github.com/legesher/tree-sitter-legesher-python) repository or the [`language-legesher-python`](https://github.com/legesher/language-legesher-python) repo 👍

**Comment by NicoleWilbur** [comment]
I'm here too as a newbie. I know just enough Python to feel like I know nothing at all, but I'm learning. And if you have any documentation needs, I can write and edit with the best of them!

**Comment by madiedgar** [comment]
Hey @NicoleWilbur 👋 ! We're all learning 😄 happy to have you here! All y'all python lovers 🐍 will have some fun things to do soon! The [`legesher-docs`](https://github.com/legesher/legesher-docs) repository holds all of our documentation if you want to look into that!

**Comment by elissavetv** [comment]
Hi @madiedgar! Thanks for the welcome. Can I pick up any issue now from those 2 repos? Or have they already been resolved? Many thanks, looking forward to helping.

**Comment by elissavetv** [comment]
Hi @madiedgar , is there a way to 'tag' issues to a specific person so we know we can work on something without overlap?

**Comment by madiedgar** [comment]
@elissavetv: Yes, wouldn't want y'all to overlap. 👍 

As an issue is first created, the label: `Status: Available` is given as it is waiting for someone to claim it. When someone claims it, the status will change to `Status: Accepted` and that person is assigned on the issue. 

We've been receiving a lot of activity in the [`legesher-translations`](https://github.com/legesher/legesher-translations) repository for new dialects and the response from Hacktoberfest has been amazing. Didn't think we'd be able to get this much of our roadmap completed 😍, so I'm grooming some issues I had saved for the next quarter to give y'all. Thanks for your patience!!

**Comment by elissavetv** [comment]
Thanks Madie! Is there anything to work on you would recommend for a beginner?

**Comment by mrmykolla** [comment]
@madiedgar Hello Madie! I would like to contribute to Open Source. I am working on Python!

**Comment by Shtihl** [comment]
Hi! I'm total beginner, but I want to contribute something to open source, what can I did?
Thanks!

**Comment by zolumasoft** [comment]
Hi @madiedgar. I am new to opensource contribution and mostly work in Python. One of the languages I speak is Xhosa (isiXhosa). I would like to help anyway I can with focus on isiXhosa.

**Comment by madiedgar** [comment]
Welcome to open source, glad to have ya'll here!! Great news!! We've been receiving SO many new translations for this project and this is the repository that plays a big part of putting it all together. I'll be adding new issues tonight, so be on the lookout for those 👍 

Hey @elissavetv 👋 !  We do our best to make this environment safe for beginners and are more than happy to come alongside you and help with any issue you choose to dedicate yourself to. The best place for beginners to open source would be to look for the `good first issue` or the `first-timers-only` tags on the repos, as well as `Technical Experience: None` or Technical Experience: Beginner`. Let me know if I can help with anything!

Hey @mrmykolla 👋 ! I love that!! I'll be making some more python related issues on this repo later tonight so stay tuned!

Hey @Shtihl 👋 !  Within this organization there are a wide variety of opportunities, many of which don't require any knowledge of coding. Is there a specific area you're wanting to grow in / contribute? 

Hey @zolumasoft 👋 I created an issue in the `legesher-translations` repository to begin the translation with isiXhosa! [We would love your help on this!](https://github.com/legesher/legesher-translations/issues/28)

**Comment by lexiewh** [comment]
Hello @madiedgar! I'm new to open source but I would love to help in any way I can. My strongest language is python but I'm open to help on anything I can! Just let me know if there is any issue that you would like me to help with.

**Comment by rominacarabathampi** [comment]
@madiedgar Hi Madie, I am interested in the translations and tree-sitter for the Romanian locale. 
I have read the READ.me files for the two projects and I believe I understood how to get started.
Please let me know if I could start working on this. 
Edit: I could also work on documentation if needed.

**Comment by JohannaHillebrand** [comment]
Hello :) I'm new with contributing to open-source-project. I can do stuff in python, C or Java, but I don't really know how to get started, could anyone point me in the right direction? :) 
(Also I'm a native german-speaker and would love help translating)

**Comment by Kobi32** [comment]
Hello Madie! I would like to contribute to Open Source. I am beginner with Pyton.

**Comment by sgayangi** [comment]
Hello :) I'm a beginner with open source projects but I would love to start learning. Is there any way in which I can help?

**Comment by ghost** [comment]
Hey. Just like many other people here, I have never really contributed to an open source project, but I'd like to get started with contributing to open source to advance my skills. Is there any way I could help here? The programming languages I'm most fluent in are Java and Python.

**Comment by MatijaBenko** [comment]
Hello, reiterating from everyone else I am very new to open-source projects and pretty much want to get my hands dirty. I would like to help in any aspect possible, it has been awhile since I had coded in python, but I should be able to succeed. I hope I may be of help!

**Comment by mohammedowais2492** [comment]
Hello, I have never contributed to any open source project before and I want to get started. Is there any way I can contribute to this project? I have experience coding in Python.

**Comment by KaiGucci** [comment]
Hi @madiedgar, I'm new to open source projects on GitHub and was wondering how I could help out. I have some experience in Python and Javascript. I am also fluent in Japanese and I would love to help translate.

**Comment by shyamcody** [comment]
Hi! I am new to open source projects on Github and I was interested to work on something based on python. Is there any issue that I can contribute to?

**Comment by hessau** [comment]
Hi! I'm knew in open source and programming but I have tried python for back-end with flask and MySQL, and JavaScript in front-end and I'm from Mexico so I can understand Spanish How could I help?

**Comment by Medham278** [comment]
Hi ! I want to contribute here. I am good with Python programming,have worked on a few personal projects as well, but have never worked with open source. Please guide me regarding how to move forward to contributing here.
