### ISSUE TITLE
docs: update README with travis & appeyor shields

### ISSUE THREAD

**Issue by madiedgar** [legesher/tree-sitter-legesher-python#16]
## README Updates
The two shields `travis` and `appeyor` in the README have a couple of minor updates. Currently, the badge does not have the `logo` or `logoColor`. The shield should look something like this: 

`https://img.shields.io/travis/com/legesher/tree-sitter-legesher-python/?style=flat-square&labelColor=black&logo=travis&logoColor=white`

<a href="https://travis-ci.com/legesher/tree-sitter-legesher-python/">
        <img src="https://img.shields.io/travis/com/legesher/tree-sitter-legesher-python/?style=flat-square&labelColor=black&logo=travis&logoColor=white" alt="macOS Build Status"></a>

**Comment by LeonardoFurtado** [comment]
Assigne me, i don't know appeyor but I will search for it
