### ISSUE TITLE
docs: update README with new project list

### ISSUE THREAD

**Issue by madiedgar** [legesher/tree-sitter-legesher-python#19]
## Update README with new project list

Yay for updated documentation! We added a new repository just for non-programmers and thus need to update our repositories project list with the new information! 🎉 

The [Legesher Projects](https://github.com/legesher/tree-sitter-legesher-python#legesher-projects) section of the README needs to be updated in the following ways:

- [ ] Add the last bullet point 
``` md
Legesher Developer Tools might be useful to you if:
- you are a non-native english speaker
- you are new to programming
- you work on a team with non-native english speakers
- you are a developer (simple enough)
```

- [ ] Add the `legesher-pride` repository as a row in the table
  - [ ] Follow the table conventions introduced by the other row items
  - [ ] Add the description: `a non-programmer's dream to contributing to open source by sharing what they know and learning what's new`

**Comment by Eshan-Agarwal** [comment]
Ok I want to pick this ?

**Comment by madiedgar** [comment]
Absolutely! I'll assign you 😄

**Comment by Eshan-Agarwal** [comment]
Can i send you PR?

**Comment by Eshan-Agarwal** [comment]
Done , I send PR
