### ISSUE TITLE
Update README link to LANGUAGE_CONVENTIONS

### ISSUE THREAD

**Issue by madiedgar** [legesher/tree-sitter-legesher-python#28]
## Update link in README

In [this section of the README file](https://github.com/legesher/tree-sitter-legesher-python#contributing), it links to a file in the `legesher` repository that is no longer there. Here is the [link to the new file](https://github.com/legesher/legesher/blob/master/LANGUAGE_CONVENTIONS.md). 

`https://github.com/legesher/legesher/blob/master/LANGUAGE_CONVENTIONS.md`

**Comment by andres-posadas** [comment]
Hello! If it is alright with you, I would like to make the PR?

**Comment by madiedgar** [comment]
Absolutely @andres-posadas! Would love that!

**Comment by andres-posadas** [comment]
Thank you so much!

**Comment by andres-posadas** [comment]
Let me know if all looks good and well!

**Comment by madiedgar** [comment]
Closing this as it was resolved in #29
