### ISSUE TITLE
Bugs in GitHub Action

### ISSUE THREAD

**Issue by wescran** [legesher/tree-sitter-legesher-python#35]
**Describe the bug**
I have been watching the GitHub actions daily so I could see it work in this repository but it took until today for me to see the errors.
1. Firstly, the action failed to make a new issue for commits made to tree-sitter python yesterday.
2. When it made an issue for commits made today, there were no labels being made.

**Expected behavior**
The action should be able to parse the commits properly and create the issue without errors or missing labels.
 
 **Possible Solution**
So I looked into why that was and found the issues and solved them. The first was that the action file was using an input variable as `inputs.issueLabels` which meant the varaible in the entrypoint script needed to be `$INPUT_ISSUELABELS` but instead was `$INPUT_LABELS` .

For the second issue I took a deeper dive to see what commits were causing the issue. In one of the commits made on tree-sitter-python, the message of the commit had literal newline `\n` characters. When this was stored in my `$commits` variable and being run through `jq` with `echo`, the statement was interpreting those characters and when being piped to jq, causing errors the filtering. Therefore I changed the statement to first construct the stored variable into json by using the `-n` null flag and then piping that into jq to successfully filter.

I'm really sorry about this bug as it was my creation in the first place. I have fixed it and tested it and have made the changes in my fork. I can make a PR when ready.

**Comment by madiedgar** [comment]
Hey @wescran, no need to apologize! I got really excited to see it all in action and that's the fun of working with a new tool! Thank you so much for already taking the time to look into this. I would love to see your changes 😄

**Comment by madiedgar** [comment]
Adding these issues for reference: #33, #34, #36. 👍

**Comment by madiedgar** [comment]
Closing this as it was resolved in #39. Thank you @wescran
