### ISSUE TITLE
Bug in GitHub Action

### ISSUE THREAD

**Issue by wescran** [legesher/tree-sitter-legesher-python#58]
**Describe the bug**
Hello @madiedgar! I had thought everything was right with my action but in the past couple of days I have been noticing some weird behavior with the shell script involved. I think I figured out what was wrong and am working on a fix now. Basically the script had poor test handling where it wasn't finding any commits but the check was resulting in a false positive. I apologize for this bug causing a spam of posts to the issues for your repositories. There is more description of the issue on my repository https://github.com/wescran/commit-issue-action/issues/30

**Expected behavior**
The action should be not creating an issue if no commits are found
 
 **Possible Solution**
Currently updating the script to have better handling of the result when no commits are found. I think once this is fixed, I can bring the change over to your repositories in a PR.

**Comment by madiedgar** [comment]
Thank you so much @wescran for looking into this! Really appreciate it. I'll keep an eye on the issue in your repo. 👍

**Comment by wescran** [comment]
I am so sorry for the wait. I have open PR's with the fix to the workflows.

**Comment by madiedgar** [comment]
No worries! Thank you so much for the update 👍

**Comment by wescran** [comment]
Hello, sorry for re-opening this issue. I found another bug from my update but have released a fix. If you want I can open another PR, or you can just change the version number to `v2.1.0` in the workflow file. Let me know what you would prefer. Thanks
