### ISSUE TITLE
style: add linting rules

### ISSUE THREAD

**Issue by madiedgar** [legesher/tree-sitter-legesher-python#7]
## Add Unibeautify Linting 

Being able to have formatted code that is aligned with the style guide is extremely important, not just for learning best practices but for the future of this project.

- [ ] Please add a `.unibeautifyrc.json` file with a linting configuration to match the languages used within this repository. 
- [ ] Please correct the current files to match the linting configurations (this should be in the details after you commit the first task^

**Comment by calra123** [comment]
Hi @madiedgar I am new to Open source, I would like to help with this issue. Do we need to add a new file ? or append it in the readme and as you mentioned above, it would be dependent on the programming language. So what exactly needs to be done ? Thanks

**Comment by madiedgar** [comment]
Hey @calra123 👋 Thanks for wanting to contribute! 🎉  Happy to have you!

To resolve this issue, it will probably include a few extra linting config files and an updated `package.json`. I'll update the issue description with a better description of the task at hand! 😄

**Comment by madiedgar** [comment]
Hey @calra123, let me know if you need any help on this! 👍

**Comment by calra123** [comment]
Sorry @madiedgar I couldn't follow up.  I actually do need help, so to get an idea of linting config files I do looked at other config files of ESLint- <https://eslint.org/docs/user-guide/getting-started>  So should I just add the linting rules of python but it depends on programmers right ? Like where they will single quotes or double quotes ? I couldn't find the language conventions file <https://github.com/legesher/legesher/blob/master/.github/language-conventions.md> , this link is not working.

**Comment by madiedgar** [comment]
No worries @calra123, I updated the issue description to hopefully be a bit clearer as to what is expected. Feel free to go through [Unibeautify](https://unibeautify.com/)'s documentation, but the assistant feature is pretty helpful in creating a config. 

Check out the [`legesher-translations`](https://assistant.unibeautify.com/#/) repository for an example.

**Comment by calra123** [comment]
Hi @madiedgar  I added the unibeautifyrc.json file for JavaScript I am yet to add it for Python and I think [issue](https://github.com/legesher/language-legesher-python/issues) specifically handles that.

**Comment by madiedgar** [comment]
Awesome @calra123, closing this issue now as it was resolved in #30
