### ISSUE TITLE
Could not install "language-legesher-python" in Atom

### ISSUE THREAD

**Issue by maxtan1999** [legesher/tree-sitter-legesher-python#71]
**Describe the bug**
By following the installation steps given in the README.md, I am stuck at the 4th step which is need to install the package, the package is not available inside the Atom while when try to redirect it from the web, I can see the installation button but it does not help me installing the package either.

**To Reproduce**
To reproduce the error:
1. Find the package is it still available in the Atom installation market

**Screenshots**
![image](https://user-images.githubusercontent.com/56993357/89607428-2169b280-d8a5-11ea-87e5-6c58ea5766c2.png)
![image](https://user-images.githubusercontent.com/56993357/89607650-9d63fa80-d8a5-11ea-8be9-aef71169fb38.png)
![image](https://user-images.githubusercontent.com/56993357/89607699-b79dd880-d8a5-11ea-8ef1-e1b00a3372ea.png)

**Comment by madiedgar** [comment]
Thanks for submitting this bug @maxtan1999, I'll look into it! 👍

**Comment by madiedgar** [comment]
Hey @maxtan1999, was able to find the source of the bug and made a patch. Check out version 0.58.3 🎉
