### ISSUE TITLE
build: clean versioning and releases from fork

### ISSUE THREAD

**Issue by madiedgar** [legesher/tree-sitter-legesher-python#9]
## Update Versions & Releases

As this project started as a fork from Tree-Sitters [`tree-sitter-python`](https://github.com/tree-sitter/tree-sitter-python), we continued from the current versioning of the original repository instead of starting anew. 

To set this apart, I think it would be helpful to do the following:
- [x] delete old versions & releases from the old repository
- [ ] start a detailed changelog
- [ ] include the current version that `tree-sitter-legesher-python` was last synced with
- [ ] implement `semantic-release` for semantic versioning in the CI build
- [ ] restart versioning & releases

**Comment by MythreyaK** [comment]
How do I get started with this?

**Comment by madiedgar** [comment]
Hey @MythreyaK, can you look into the [`semantic-release`](https://www.npmjs.com/package/semantic-release) package and see what we need to implement to our project to successfully use this? 

I can get you the information for the version of tree-sitter-python it is synced with and delete the releases that aren't from this specific project. 😄

**Comment by MythreyaK** [comment]
From what I've understood, the first step needs to be completed by the repo maintainer, since `semantic-release` asks for GitHub and npm credentials, with additional setup. After that, I can change the `.travis.yml` and `package.json` files. 
<sub>*Newbie here! Do let me know if I'm off track </sub>

**Comment by madiedgar** [comment]
I believe you are absolutely right! Let's tag team this and complete this together 👍 I'll go through and complete step 1. 

Could you look into plugins (or like items) that could help us keep track of changelogs? This would be wonderful to put into practice, but want to have an informed start.

**Comment by MythreyaK** [comment]
Okay! 

I looked around and this package <code>[auto-changelog](https://www.npmjs.com/package/auto-changelog)</code>. It is able to automatically parse semantic versioning and git commit history to generate the changelog file. An example generated by the npm package is [here](https://github.com/CookPete/auto-changelog/blob/HEAD/CHANGELOG.md).

**Comment by MythreyaK** [comment]
Any updates?

**Comment by madiedgar** [comment]
Hey @MythreyaK, I just opened an [issue](https://github.com/atom/apm/issues/870) on Atom's repo to see if they could help. 🤞 it gets resolved soon 😄 Thank you for your patience. 

I looked into `auto-changelog` and it seems it does exactly what we're looking for! 👍

**Comment by MythreyaK** [comment]
Sure thing!

I found similar issues to the one you raised [on discuss](https://discuss.atom.io/t/cant-publish-package/4890/4), [here](https://github.com/atom/apm/issues/218) and [here](https://github.com/atom/apm/issues/147).

🤞

**Comment by madiedgar** [comment]
Thank you @MythreyaK for all the help! You're amazing!! 

We had some activity on the issue and they're going to try to redirect the atom package to this repository (I had it attached to another user). Hopefully it should be resolved soon 🤞 Thank you again for your patience!!!

**Comment by MythreyaK** [comment]
Okay!
My pleasure!

**Comment by madiedgar** [comment]
Hey @MythreyaK, just wanted to check in and let you know I haven't forgotten about this. We're still waiting on the issue from Atom to be resolved, but in the meantime please know how grateful I am. 

Excited to continue working on this soon!

**Comment by MythreyaK** [comment]
I was just going to comment to know the status! 
My pleasure! 
I'm learning things, so thank you! My exams have just finished, so I'll try drafting the PR and I'll let you know when it's ready.
